FROM node:16-alpine

RUN apk add \
  bash \
  luarocks5.1 \
  zip \
  su-exec \
  g++ \
  make \
  python3 \
  openrc

RUN mkdir -p /data

WORKDIR /backend
COPY integrations-service/backend/package.json ./
COPY integrations-service/backend/scripts/copyLibs.js ./scripts/
RUN npm i && npm cache clean --force

WORKDIR /frontend
COPY integrations-service/frontend/package.json ./
COPY integrations-service/frontend/scripts/copyLibs.js ./scripts/
RUN npm i

WORKDIR /shared
COPY integrations-service/shared .
COPY integrations-service/shared/package.json ./
RUN npm i && npm cache clean --force

WORKDIR /backend
COPY integrations-service/backend/src ./src/
COPY integrations-service/backend/scripts/wait-for-it.sh .

RUN npm run postinstall
RUN npm run copy-libs

WORKDIR /frontend
COPY integrations-service/frontend ./
RUN npm run copy-libs

RUN npm run build 
RUN mkdir /backend/src/dist
RUN mkdir /backend/src/dist/integrations
RUN cp dist/index.html /backend/src/dist/
RUN cp dist/favicon_.ico /backend/src/dist/
RUN mv dist/* /backend/src/dist/integrations

WORKDIR /backend
USER node

COPY integrations-service/entrypoint.sh .
ENTRYPOINT [ "/backend/entrypoint.sh" ]

CMD npm run start
